### ISSUE TITLE
您好大神，找您有事

### ISSUE THREAD

**Issue by chenfenggen** [PengHaiZhuo/PhotoPicker#1]
我最近在maven仓库的网站上找不到您的项目了，可能被清除了。所以导致我用您的PhotoPicker项目在android端下载依赖失败，本想用您的源代码自己编译出一个aar包，结果又提示您依赖的PhotoView项目无法下载，这个项目所在的仓库也有问题。其实自己已经打算自己开发一个类似的功能，但还是抱着试一下的心态联系您。看您那里有没有编译好的离线aar包。我也不清楚您的项目为何不在maven仓库了。我的联系方式739314028@qq.com，期待您的回复。

**Comment by PengHaiZhuo** [comment]
你好，我这里没有离线aar包，有尝试更换依赖源吗，尝试：https://developer.aliyun.com/mvn/guide。并把maven { url 'https://jitpack.io' }添加到配置文件。不知道你是是使用kotlin还是java，这个项目包括这个项目的依赖都挺老了，可能是你的软件版本太高。我已经很久没做Android了，祝你顺利。

**Comment by chenfenggen** [comment]
好的，谢谢， 因为我的项目依赖您的项目，但也不是经常修改我的项目，所以也不清楚是我更新了android studio到最新版的原因还是什么原因，最终我还是确定为跟依赖源没什么关系， 是您项目没在仓库的问题。您的项目没在maven仓库了，而您项目的依赖PhotoView这个项目也是下载不下来的，也是很多年没有维护的那种。我已经准备自己重新写个类似的功能了，正在研究相关代码。从依赖您的项目得到的经验教训就是：不能过度依赖他人项目啊，因为环境一直都在不断变化，当然还是离线的包更稳固，留个后手总要好些。您看下您现在在您自己的电脑上的android studio能编译您这个项目吗。能的话还拜托发送个aar离线包给我，我是个念旧的人，哈哈，能用的话还是继续用。

**Comment by PengHaiZhuo** [comment]
你好，包含第三方依赖的aar包我听说过fat aar，具体我没弄过，普通aar是没有循环依赖的，需要自己手动导一遍第三方依赖，我认为最好的方式是从仓库获取，我帮你搜了一下，你可以参考下添加阿里云镜像https://developer.aliyun.com/mvn/guide，我的demo里缺少了maven {url 'https://maven.aliyun.com/repository/central'}，请添加上再试试。希望有帮到你

**Comment by chenfenggen** [comment]
感谢您的回复，您说的方法我都试过了，都是报无法解析我依赖您的库，同时您依赖的那个photoview库也是这样，所以想找您要aar包这路不行，想用您的代码编译自己生成aar包也不行。我已经在自己弄相同功能的代码了，虽说性能差了点，但至少可以实现同样的功能了，祝您好运！
